### ISSUE TITLE
read issue

### ISSUE THREAD

**Issue by thiva7** [antonagre/Pjsua2_base#1]
Traceback (most recent call last):
  File "C:\Users\USER\Desktop\pygui\Pjsua2_base-master\application.py", line 175, in <module>
    main()
  File "C:\Users\USER\Desktop\pygui\Pjsua2_base-master\application.py", line 171, in main
    app.start()
  File "C:\Users\USER\Desktop\pygui\Pjsua2_base-master\application.py", line 74, in start
    self.appConfig.loadFile(cfg_file)
  File "C:\Users\USER\Desktop\pygui\Pjsua2_base-master\settings.py", line 59, in loadFile
    self.epConfig.readObject(root)
  File "C:\Users\USER\Desktop\pygui\pjsua2.py", line 6867, in readObject
    return _pjsua2.EpConfig_readObject(self, node)
pjsua2.Error

**Comment by 870561859** [comment]
Hey friend, have you solved it yet
